### PR TITLE
Reference Documents

### PR DESCRIPTION
**Pull request by SpudGunMan**
idea to add basic ARRL and ICOM reference materials to the desktop. could add more like winlink/pat stuff?

### CODE REVIEW

**Comment by km4ack** [comment]
I like this idea. The only issue I see is the use of "~" [here](https://github.com/km4ack/pi-build/pull/446/commits/3955028c141adc3238f7e0aee9f456b1ce48f5fc#diff-e97aaa019b63141e25845f7f439ed5fb8436f38cd9021dcee9cb1df3bdfc6538R519) Let's change this to $HOME to stay consistent with the rest of the code.

**Comment by km4ack** [comment]
One other thought on this....should the reference material be placed in the Documents directory and a symlink placed on the desktop? What's your opinion?

**Comment by SpudGunMan** [comment]
my initial thought was people likely move it or remove it as they like anyway (why I didnt add any checking of the files once downloaded as well)

I will move them to Documents and link to desktop however that is a better place for them

**Comment by km4ack** [comment]
One last minor detail. Change `mkdir` to `mkdir -p` so it doesn't throw an error if the directory exist. https://github.com/km4ack/pi-build/pull/446/commits/44f1bd917132f7947c2ae3643e2753d58fbb4188#diff-d8b15701c41ea5ee75aa2f94aa53977d5fc9b1588102cd32fe55d6e7706b8fd7R947

**Comment by SpudGunMan** [comment]
done

**Pull request merged**
