### PR TITLE
fix TQSL app.check

### PR DESCRIPTION
**Pull request by SpudGunMan**
didnt test live as I dont have a downgraded system but appears to work did run it thru bash

### CODE REVIEW

**Comment by km4ack** [comment]
PR has conflicts with dev branch. Please resolve.

**Comment by SpudGunMan** [comment]
yea this was fixed before the app.check patch, I fixed this haven't tested it yet doing that soon

**Comment by SpudGunMan** [comment]
hold this patch till clear

**Comment by SpudGunMan** [comment]
merged to app check patch closing

**Pull request closed without merging**
