### PR TITLE
Add support for Home SSID with spaces in name

### PR DESCRIPTION
**Pull request by kuperman**

### CODE REVIEW

**Comment by kuperman** [comment]
Current version only takes the first part of the SSID name. I modified it to take everything after the "SSID: " instead. I am happy to detail the sed command if that would be useful.

**Comment by kuperman** [comment]
Just read issue #161 and will modify to make the second change.

**Comment by kuperman** [comment]
Sigh. Update script looks like it'll need a bit more tweaking which I can't get to at the moment. Sorry for all the notification emails.

**Comment by km4ack** [comment]
Thanks for working on this. When you resubmit the patch, please submit against the dev branch of code. 73, de KM4ACK

**Pull request closed without merging**
