### PR TITLE
General Formatting and Syntax. Fixed a few dangerous rm statments too.

### PR DESCRIPTION
**Pull request by hsmalley**
Hi Jason! Love the videos and I saw this as a way I could use my professional skills to give back. I did some general formatting and syntax checking on this. There were a few things in there like the rm and cd statements that could be dangerous so I brought those up to best practices too. Since I did a once over on it I might have missed a few things. Please review it and test it to see if it meets your needs. If it doesn't then let me know and I'll be happy to submit another merge request (if it's wanted.) Thanks! 73 W4UGH

### CODE REVIEW

**Comment by km4ack** [comment]
Thanks! Could you submit the changes against the dev branch of code please instead of master.

**Comment by hsmalley** [comment]
Done

**Comment by km4ack** [comment]
Thanks.

**Comment by km4ack** [comment]
One issue I have spotted is the addition of `|| exit` in multiple places. We don't want the script to exit just because one thing fails. Too often, one application changes (moves, website down, fails to build, etc). I prefer for this one failure not to cause the entire script to stop. For instance, there is a currently know bug where [xlog will not build](https://github.com/km4ack/pi-build/issues/215) This caused the script to stop at this point instead of just failing to install xlog and continuing with the rest.
Screen Shot 2021-03-17 at 4 31 12 AM

**Comment by hsmalley** [comment]
Hmm, that's a problem for sure! There's a few ways of resolving that, for the functions a `|| return` will make sure nothing bad happens and for the rest something like `|| ! echo "Failure"` would give an error but continue the rest of the script. I think that would work better, what do you think?

**Comment by km4ack** [comment]
Either should be fine. I'll load your latest changes and start a new build.

**Comment by km4ack** [comment]
After the build I gave things a quick test and found that direwolf wasn't installed. 
base.function line 142
`(mkdir build && cd build) || return`
creates the dir but doesn’t move to the new dir. Hence the build fails.

Other than that, everything appears ok.

**Comment by hsmalley** [comment]
Fixed!

**Pull request merged**
